# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-27 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vod_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vod',
            name='load_in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vod',
            name='all_messages_loaded',
            field=models.BooleanField(default=False),
        ),
    ]
