# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vod_stats', '0004_auto_20170228_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vod',
            old_name='vod_id',
            new_name='id',
        ),
    ]
